kind: pipeline
type: docker
name: default

steps:
  - name: build-jar
    image: maven:3.6.3-jdk-8-slim
    privileged: true
    volumes:
      - name: maven_cache
        path: /root/.m2
    commands:
      - mvn clean package -DskipTests

  - name: build-img
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      tags: latest
      username:
        from_secret: loginName
      password:
        from_secret: pwd
      repo: zyw090111@163.com/zyw/drone-demo
      registry: zyw090111@163.com
      debug: true

volumes:
  - name: maven_cache
    host:
      path: /mnt/maven_cache