kind: pipeline
type: docker
name: default

steps:
  - name: build-jar
    image: maven:3.6.3-jdk-8-slim
    privileged: true
    volumes:
      - name: maven_cache
        path: /root/.m2
    commands:
      - mvn clean package -DskipTests

  - name: build-img
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      tags: latest
      username:
        from_secret: loginNam
      password:
        from_secret: pwd
      repo: drone-harbor.powertime.cn:444/library/drone-demo:v1.0.0
      registry: drone-harbor.powertime.cn:444

volumes:
  - name: maven_cache
    host:
      path: /mnt/maven_cache