kind: pipeline
type: docker
name: default

steps:
  - name: build-jar
    image: maven:3.6.3-jdk-8-slim
    privileged: true
    volumes:
      - name: maven_cache
        path: /root/.m2
    commands:
      - mvn clean package -DskipTests

  - name: build-img
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      tags: latest
      username:
        from_secret: loginName
      password:
        from_secret: pwd
      repo: 192.168.1.161:444/library/drone-demo
      registry: 192.168.1.161:444
      debug: true
      custom_dns:
        - 192.168.1.161

volumes:
  - name: maven_cache
    host:
      path: /mnt/maven_cache