kind: pipeline
type: docker
name: default

steps:
  # 编译构件java代码
  - name: build-jar
    image: maven:3.6.3-jdk-8-slim
    privileged: true
    volumes:
      - name: maven_cache
        path: /root/.m2
    commands:
      - mvn clean package -DskipTests

  # 打包docker镜像到仓库
  - name: build-img
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      tags: latest
      username:
        from_secret: loginName
      password:
        from_secret: pwd
      repo: registry.cn-hangzhou.aliyuncs.com/zywlxh/drone-demo
      registry: registry.cn-hangzhou.aliyuncs.com
      debug: true
  # 利用ssh插件部署应用到知道服务器
#  - name: deploy
#    image: appleboy/drone-ssh
#    settings:
#      host: 192.168.1.154
#      username: root
#      password: root
#      port: 22
#      script:
#        docker run -d --name drone-demo -p 9999:9999 registry.cn-hangzhou.aliyuncs.com/zywlxh/drone-demo
# 利用kubectl镜像部署镜像到k8s或者rancher
  - name: deploy-kube
    image: bitnami/kubectl
    volumes:
      - name: kube-config
        path: /.kube/config
    commands:
      - kubectl apply -f kubernetes.yaml
    when:
      event: [push]
      status: [ success ]

volumes:
  - name: maven_cache
    host:
      path: /mnt/maven_cache
  - name: kube-config
    host:
      path: /mnt/kubectl/config