kind: pipeline
type: docker
name: default

clone:
  disable: true

steps:
  - name: clone
    commands:
      - git clone http://192.168.1.160:3000/powertime/drone-demo.git .
      - git checkout $DRONE_COMMIT

  - name: build-jar
    image: maven:3.6.3-jdk-8-slim
    commands:
      - mvn clean package

  - name: build-img
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      username:
        from_secret: loginNam
      password:
        from_secret: pwd
      repo: drone-harbor.powertime.cn:444/library/drone-demo:v1.0.0
      registry: drone-harbor.powertime.cn:444