# 定义服务
apiVersion: v1
kind: Service
metadata:
  name: drone-demo-service
spec:
  selector:
    app: drone-demo
  ports:
    - protocol: TCP
      port: 8080            # 服务端口, 内部可访问
      targetPort: 9999      # 目标端口, 此处指的是pod的8080端口
#      nodePort: 30080		# 节点端口, 外部可访问
  type: NodePort
---
#定义Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-demo
  labels:
    app: drone-demo
spec:
  replicas: 2
  template:
    metadata:
      name: drone-demo
      labels:
        app: drone-demo
    spec:
      containers:
        - name: drone-demo
          image: registry.cn-hangzhou.aliyuncs.com/zywlxh/drone-demo
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
      restartPolicy: Always
  selector:
    matchLabels:
      app: drone-demo

---
# 定义Ingress
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: drone-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: drone.v5cn.cn
      http:
        paths:
          - path: /
            backend:
              serviceName: drone-demo-service
              servicePort: 8080
  