apiVersion: v1
kind: Service
metadata:
  name: drone-demo-service
spec:
  selector:
    app: drone-demo
  ports:
    - protocol: TCP
      port: 8080            # 服务端口, 内部可访问
      targetPort: 9999      # 目标端口, 此处指的是pod的8080端口
#      nodePort: 30080		# 节点端口, 外部可访问
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-demo
  labels:
    app: drone-demo
spec:
  replicas: 1
  template:
    metadata:
      name: drone-demo
      labels:
        app: drone-demo
    spec:
      containers:
        - name: drone-demo
          image: registry.cn-hangzhou.aliyuncs.com/zywlxh/drone-demo
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
      restartPolicy: Always
  selector:
    matchLabels:
      app: drone-demo